### PR TITLE
chore: clippy fixes

### PR DESCRIPTION
**Pull request by knvi**
hey,

made some small changes to the code to get rid of **most** of the clippy errors (ran clippy with clippy::pedantic, all, cargo, nursery). builds just fine.

cheers

### CODE REVIEW

**Review by neverabsolute — APPROVED** [review]
lgtm 👍

**Comment by TheLDB** [comment]
lgtm. kunevi 100x dev, best dev. 

hire him while you're at it

**Comment by iKeaton** [comment]
LGTM!

**Comment by alsonick** [comment]
Lgtm!! 👍

**Comment by alii** [comment]
LGTV
image

**Review by alii — APPROVED** [review]

**Review by neverabsolute — APPROVED** [review]
price_1Mb5WDB9plQLUnXoGUUE7P 👍

**Comment by pxseu** [comment]
hi, 
clippy pedantic is the highest lint level and im not getting *any* of the lints you got except clippy cargo which are different. everything is always linted with `cargo +nightly clippy` running bleading edge version if dependencies allow or stable. could you elaborate how you got to this?

**Comment by knvi** [comment]
I added 
```rust
#![warn(
clippy::all,
clippy::pedantic,
clippy::nursery,
clippy::cargo
)]
```
to the beginning of the `lib.rs` file. I'm running stable toolchain, perhaps that's why. Even if not for the clippy lints, then those are general code improvements

**Comment by pxseu** [comment]
oh yeah no doubt in that, just was wondering since i haven't seen these get flagged before

**Review by pxseu — APPROVED** [review]
LGTM!

**Pull request merged**
